-- MySQL Script generated by MySQL Workbench
-- Mon Nov  6 16:15:08 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Restaurante_Hoteleria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Restaurante_Hoteleria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Restaurante_Hoteleria` DEFAULT CHARACTER SET utf8 ;
USE `Restaurante_Hoteleria` ;

-- -----------------------------------------------------
-- Table `Restaurante_Hoteleria`.`Receta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurante_Hoteleria`.`Receta` (
  `idReceta` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Procedimiento` LONGTEXT NOT NULL,
  `tiempoPreparacion` VARCHAR(12) NOT NULL,
  `numeroPersonas` INT NOT NULL,
  PRIMARY KEY (`idReceta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante_Hoteleria`.`Platillo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurante_Hoteleria`.`Platillo` (
  `idPlatillo` INT(11) NOT NULL AUTO_INCREMENT,
  `nombrePlatillo` VARCHAR(45) NOT NULL,
  `descripcionPlatillo` VARCHAR(200) NOT NULL,
  `costoPlatillo` FLOAT NOT NULL,
  `receta_idReceta` INT NOT NULL,
  PRIMARY KEY (`idPlatillo`),
  INDEX `FK_idReceta_idx` (`receta_idReceta` ASC),
  CONSTRAINT `FK_idReceta`
    FOREIGN KEY (`receta_idReceta`)
    REFERENCES `Restaurante_Hoteleria`.`Receta` (`idReceta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante_Hoteleria`.`Mesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurante_Hoteleria`.`Mesa` (
  `idMesa` INT(11) NOT NULL AUTO_INCREMENT,
  `noMesa` INT(11) NOT NULL,
  `capacidad` INT(11) NOT NULL,
  PRIMARY KEY (`idMesa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante_Hoteleria`.`tipoProducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurante_Hoteleria`.`tipoProducto` (
  `idTipoProducto` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante_Hoteleria`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurante_Hoteleria`.`productos` (
  `idProducto` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `precio` FLOAT NOT NULL,
  `tipoProducto_idTipoProducto` INT NOT NULL,
  PRIMARY KEY (`idProducto`),
  INDEX `fk_productos_tipoProducto1_idx` (`tipoProducto_idTipoProducto` ASC),
  CONSTRAINT `fk_productos_tipoProducto1`
    FOREIGN KEY (`tipoProducto_idTipoProducto`)
    REFERENCES `Restaurante_Hoteleria`.`tipoProducto` (`idTipoProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante_Hoteleria`.`detalleRecetaIngrediente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurante_Hoteleria`.`detalleRecetaIngrediente` (
  `receta_idReceta` INT NOT NULL,
  `PesoOcantidad` VARCHAR(45) NOT NULL,
  `productos_idProducto` INT NOT NULL,
  INDEX `FK_idReceta_idx` (`receta_idReceta` ASC),
  PRIMARY KEY (`receta_idReceta`),
  INDEX `fk_detalleRecetaIngrediente_productos1_idx` (`productos_idProducto` ASC),
  CONSTRAINT `FK_idReceta2`
    FOREIGN KEY (`receta_idReceta`)
    REFERENCES `Restaurante_Hoteleria`.`Receta` (`idReceta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalleRecetaIngrediente_productos1`
    FOREIGN KEY (`productos_idProducto`)
    REFERENCES `Restaurante_Hoteleria`.`productos` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante_Hoteleria`.`Ingrediente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurante_Hoteleria`.`Ingrediente` (
  `idIngrediente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `unidadMedida` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idIngrediente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante_Hoteleria`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurante_Hoteleria`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nombreCliente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante_Hoteleria`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurante_Hoteleria`.`Pedido` (
  `idPedido` INT(11) NOT NULL AUTO_INCREMENT,
  `fechaPedido` VARCHAR(10) NOT NULL,
  `mesa_idMesa` INT(11) NOT NULL,
  `cliente_idCliente` INT(11) NOT NULL,
  PRIMARY KEY (`idPedido`, `mesa_idMesa`, `cliente_idCliente`),
  INDEX `FK_idMesa_idx` (`mesa_idMesa` ASC),
  INDEX `FK_idCliente_idx` (`cliente_idCliente` ASC),
  CONSTRAINT `FK_idMesa`
    FOREIGN KEY (`mesa_idMesa`)
    REFERENCES `Restaurante_Hoteleria`.`Mesa` (`idMesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_idCliente`
    FOREIGN KEY (`cliente_idCliente`)
    REFERENCES `Restaurante_Hoteleria`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante_Hoteleria`.`detallepedidoplatillo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurante_Hoteleria`.`detallepedidoplatillo` (
  `cantidadPlatillo` INT(11) NOT NULL,
  `pedido_idPedido` INT(11) NOT NULL,
  `pedido_idPlatillo` INT(11) NOT NULL,
  INDEX `FK_idPedido_idx` (`pedido_idPedido` ASC),
  INDEX `FK_idPlatillo_idx` (`pedido_idPlatillo` ASC),
  PRIMARY KEY (`pedido_idPedido`, `pedido_idPlatillo`),
  CONSTRAINT `FK_idPedido`
    FOREIGN KEY (`pedido_idPedido`)
    REFERENCES `Restaurante_Hoteleria`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_idPlatillo`
    FOREIGN KEY (`pedido_idPlatillo`)
    REFERENCES `Restaurante_Hoteleria`.`Platillo` (`idPlatillo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante_Hoteleria`.`detallepedidobebida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurante_Hoteleria`.`detallepedidobebida` (
  `cantidadBebida` INT(11) NOT NULL,
  `pedido_idPedido` INT(11) NOT NULL,
  `productos_idProducto` INT NOT NULL,
  INDEX `FK_idPedido_idx` (`pedido_idPedido` ASC),
  PRIMARY KEY (`pedido_idPedido`),
  INDEX `fk_detallepedidobebida_productos1_idx` (`productos_idProducto` ASC),
  CONSTRAINT `FK_idPedido2`
    FOREIGN KEY (`pedido_idPedido`)
    REFERENCES `Restaurante_Hoteleria`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detallepedidobebida_productos1`
    FOREIGN KEY (`productos_idProducto`)
    REFERENCES `Restaurante_Hoteleria`.`productos` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante_Hoteleria`.`Bebida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurante_Hoteleria`.`Bebida` (
  `idBebida` INT NOT NULL AUTO_INCREMENT,
  `nombreBebida` VARCHAR(45) NOT NULL,
  `descripcionBebida` VARCHAR(150) NULL,
  `costoBebida` FLOAT NOT NULL,
  PRIMARY KEY (`idBebida`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante_Hoteleria`.`tipoMedida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurante_Hoteleria`.`tipoMedida` (
  `idTipoMedida` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoMedida`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante_Hoteleria`.`bodega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurante_Hoteleria`.`bodega` (
  `idBodega` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `nivel` VARCHAR(45) NULL,
  `capacidad` VARCHAR(45) NULL,
  `encargado` VARCHAR(45) NULL,
  PRIMARY KEY (`idBodega`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante_Hoteleria`.`detallebodega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurante_Hoteleria`.`detallebodega` (
  `idDetalleBodega` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `productos_idProducto` INT NOT NULL,
  `bodega_idBodega` INT NOT NULL,
  `tipoMedida_idTipoMedida` INT NOT NULL,
  PRIMARY KEY (`idDetalleBodega`),
  INDEX `fk_detallebodega_productos1_idx` (`productos_idProducto` ASC),
  INDEX `fk_detallebodega_bodega1_idx` (`bodega_idBodega` ASC),
  INDEX `fk_detallebodega_tipoMedida1_idx` (`tipoMedida_idTipoMedida` ASC),
  CONSTRAINT `fk_detallebodega_productos1`
    FOREIGN KEY (`productos_idProducto`)
    REFERENCES `Restaurante_Hoteleria`.`productos` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detallebodega_bodega1`
    FOREIGN KEY (`bodega_idBodega`)
    REFERENCES `Restaurante_Hoteleria`.`bodega` (`idBodega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detallebodega_tipoMedida1`
    FOREIGN KEY (`tipoMedida_idTipoMedida`)
    REFERENCES `Restaurante_Hoteleria`.`tipoMedida` (`idTipoMedida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
